# ============================================================
# docker-compose.yml
#
# This file makes it easy for anyone to start the analysis
# environment with one short command instead of a long
# "docker run" command with many flags.
#
# HOW TO USE:
#   docker compose up -d
# 
# HOW TO TURN OFF:
#   docker compose down
#
# Then open the URL printed in the terminal (starts with
# http://127.0.0.1:8787)
# 
# Credentials for login: 
# - username = rstudio
# - password = password 
#
# ============================================================

services:
  analysis-env:
    image: awong62/dsci-310-group-04:latest

    # do this for local development
    # image: dsci-310-project:quarto-0.0.1

    environment:
    - PASSWORD=password
    ports:
      - "8787:8787"

    volumes:
      - ./data:/home/rstudio/work/data
      - ./reports:/home/rstudio/work/reports
      - ./results:/home/rstudio/work/results
      - ./src:/home/rstudio/work/src
      - ./docs:/home/rstudio/work/docs
      - ./tests:/home/rstudio/work/tests
