## Methods and Results 

```{r}
#| include: false
library(tidyverse)
library(knitr)
```

### Dataset Description
To start off the analysis, we can examine the available features in the data. This information is referenced from the official data source (UCI Machine Learning Repository: Online Shoppers Purchasing Intention Dataset).
Each row/data point represents one user session.

::: {#tbl-numerical-feature-description}

| Feature  | Type | Feature Description |
|----------------|-------------|------------------------|
| Administrative  | Integer | Number of administrative pages viewed per session |
| Administrative_Duration  | Integer | Total time spent on administrative pages per session |
| Informational  | Integer | Number of informational pages viewed per session |
| Informational_Duration  | Integer | Total time spent on informational pages per session |
| ProductRelated  | Integer | Number of product related pages viewed per session |
| ProductRelated_Duration  | Continuous | Number of product related pages viewed per session |
| BounceRates  | Continuous | Inverse of engagement rate (From Google Analytics) |
| ExitRates  | Continuous | Last page before stopping the user session (From Google Analytics) |
| PageValues  |  Integer | Average value each page contributes to the user session (From Google Analytics) |
| SpecialDay  | Integer | Closeness of the site visited date to a "special date" where purchase are more likely |

Numerical Features
:::

::: {#tbl-categorical-feature-description}

| Feature  | Feature Description |
|----------------|-------------|
| Month  | Month of session |
| OperatingSystems | Operating system used for session |
| Browser  | Browser used for session |
| Region | Geographic region of session |
| TrafficType | Traffic source of session (banner, direct, SMS, etc.) |
| VisitorType | Visitor type of session (New, Returning, etc.) |
| Weekend  | Binary value indicating the session occurred on a weekend |

Categorical Features
:::

::: {#tbl-target-variable-description}

| Target Variable  | Variable Description |
|----------------|-------------|
| Revenue  | Binary class label indicating whether the user session ended in a purchase |

Target Variable
:::

Knowing the expected data types of each feature, we can proceed with data cleaning to prepare for EDA and analysis.
